In [1]:
import numpy as np

In [17]:
x = np.arange(0,21)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
x[8]

8

In [23]:
x[-1]

20

In [25]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
x[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[-10:-1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
y = x[5:10] = 40

In [37]:
x

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [39]:
y = x.copy()

In [41]:
y

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])