In [2]:
import numpy as np

In [4]:
x = [1,2,3,4,5]

In [6]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(x)

array([1, 2, 3, 4, 5])

In [10]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.zeros((3,2)) + 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
x = np.array(x)

In [44]:
x

array([1, 2, 3, 4, 5])

In [46]:
x.max()

5

In [58]:
x.argmax()

4

In [48]:
x.min()

1

In [60]:
x.argmin()

0

In [52]:
np.random.rand(5)

array([0.96351399, 0.64856158, 0.69064631, 0.66062036, 0.4200435 ])

In [54]:
np.random.randn(5)

array([-1.48419344, -1.53460227,  0.05991567,  0.31424021, -1.17660899])

In [56]:
np.random.randint(5)

4