In [2]:
import numpy as np

In [6]:
x = np.arange(25).reshape(5,5) 

In [8]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
x[2][2]

12

In [12]:
x[2,2]

12

In [14]:
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [16]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
x[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [22]:
x[3:,2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [24]:
y= np.arange(20)

In [26]:
y>15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [28]:
y[y>12]

array([13, 14, 15, 16, 17, 18, 19])