In [2]:
import numpy as np

In [6]:
x = np.arange(10)

In [8]:
y = np.arange(10,20)

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
z = x+y

In [16]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
z = x-y

In [20]:
z

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [22]:
z = x*y

In [24]:
z

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [26]:
z =x/y

In [28]:
z

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [30]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [32]:
np.log(x)

/var/folders/zg/dr1dfh1x4rvct__ws9tns1h40000gn/T/ipykernel_35265/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [34]:
np.max(x)

9

In [36]:
x = np.arange(12).reshape(3,4)

In [38]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
y = np.arange(10,22).reshape(3,4)

In [42]:
y

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [44]:
x+y

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [46]:
# 1. Import NumPy
# import numpy as np

# 2. Create a NumPy array
# arr = np.array([1, 2, 3])

# 3. Generate an array of zeros
# zeros = np.zeros((2, 3))

# 4. Generate an array of ones
# ones = np.ones((3, 2))

# 5. Create an identity matrix
# identity = np.eye(3)

# 6. Create an array with a range of numbers
# arange = np.arange(0, 10, 2)

# 7. Create an array of evenly spaced numbers
# linspace = np.linspace(0, 1, 5)

# 8. Generate random numbers from a uniform distribution
# random_uniform = np.random.rand(3, 3)

# 9. Generate random integers
# random_integers = np.random.randint(0, 10, size=(3, 3))

# 10. Generate random numbers from a normal distribution
# random_normal = np.random.randn(3, 3)

# 11. Reshape an array
# reshaped = arr.reshape(3, 1)

# 12. Flatten an array
# flattened = arr.flatten()

# 13. Transpose a matrix
# transposed = arr.T

# 14. Element-wise addition
# added = arr1 + arr2

# 15. Element-wise subtraction
# subtracted = arr1 - arr2

# 16. Element-wise multiplication
# multiplied = arr1 * arr2

# 17. Element-wise division
# divided = arr1 / arr2

# 18. Dot product of matrices
# dot_product = np.dot(arr1, arr2)

# 19. Matrix multiplication
# matmul = np.matmul(arr1, arr2)

# 20. Calculate the inverse of a matrix
# inverse = np.linalg.inv(matrix)

# 21. Calculate the determinant of a matrix
# determinant = np.linalg.det(matrix)

# 22. Calculate eigenvalues and eigenvectors
# eigenvalues, eigenvectors = np.linalg.eig(matrix)

# 23. Calculate the norm of a vector
# norm = np.linalg.norm(vector)

# 24. Calculate the rank of a matrix
# rank = np.linalg.matrix_rank(matrix)

# 25. Solve a system of linear equations
# solution = np.linalg.solve(A, b)

# 26. Calculate the trace of a matrix
# trace = np.trace(matrix)

# 27. Find the mean of an array
# mean = np.mean(arr)

# 28. Find the median of an array
# median = np.median(arr)

# 29. Find the standard deviation of an array
# std = np.std(arr)

# 30. Find the variance of an array
# variance = np.var(arr)

# 31. Find the minimum value in an array
# min_val = np.min(arr)

# 32. Find the maximum value in an array
# max_val = np.max(arr)

# 33. Calculate the sum of array elements
# sum_val = np.sum(arr)

# 34. Find the index of the minimum value
# argmin = np.argmin(arr)

# 35. Find the index of the maximum value
# argmax = np.argmax(arr)

# 36. Sort an array
# sorted_array = np.sort(arr)

# 37. Concatenate arrays
# concatenated = np.concatenate((arr1, arr2), axis=0)

# 38. Stack arrays vertically
# vstacked = np.vstack((arr1, arr2))

# 39. Stack arrays horizontally
# hstacked = np.hstack((arr1, arr2))

# 40. Split an array
# split = np.split(arr, 3)

# 41. Tile an array
# tiled = np.tile(arr, (2, 2))

# 42. Repeat elements of an array
# repeated = np.repeat(arr, 2)

# 43. Find unique elements in an array
# unique_elements = np.unique(arr)

# 44. Check for NaN values
# has_nan = np.isnan(arr)

# 45. Replace NaN values
# replaced_nan = np.nan_to_num(arr)

# 46. Apply a function element-wise
# applied = np.vectorize(lambda x: x**2)(arr)

# 47. Boolean masking
# masked = arr[arr > 5]

# 48. Create a diagonal matrix
# diagonal_matrix = np.diag([1, 2, 3])

# 49. Calculate the cumulative sum
# cumulative_sum = np.cumsum(arr)

# 50. Calculate the cumulative product
# cumulative_product = np.cumprod(arr)


In [48]:
x.sum()

66

In [52]:
m = np.full(3,3),True

In [54]:
m

(array([3, 3, 3]), True)

In [58]:
np.intersect1d(x,y)

array([10, 11])